//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualDoctor.Shared.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualDoctor.Shared.Config.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully added new item in database..
        /// </summary>
        public static string AddingSuccess {
            get {
                return ResourceManager.GetString("AddingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &gt;&gt;.
        /// </summary>
        public static string AddRight {
            get {
                return ResourceManager.GetString("AddRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air quality.
        /// </summary>
        public static string AirQuality {
            get {
                return ResourceManager.GetString("AirQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Previous.
        /// </summary>
        public static string BackwardsButton {
            get {
                return ResourceManager.GetString("BackwardsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth place.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic.
        /// </summary>
        public static string Clinic {
            get {
                return ResourceManager.GetString("Clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinics.
        /// </summary>
        public static string Clinics {
            get {
                return ResourceManager.GetString("Clinics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country name.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current clinics.
        /// </summary>
        public static string CurrentClinics {
            get {
                return ResourceManager.GetString("CurrentClinics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been database error. 
        ///Detailed message is in log file..
        /// </summary>
        public static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully deleted item from database..
        /// </summary>
        public static string DeletingSuccess {
            get {
                return ResourceManager.GetString("DeletingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        public static string Doctors {
            get {
                return ResourceManager.GetString("Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinking water quality.
        /// </summary>
        public static string DrinkingWaterQuality {
            get {
                return ResourceManager.GetString("DrinkingWaterQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation could not be
        ///performed, because item already
        ///exists in database..
        /// </summary>
        public static string EntityExists {
            get {
                return ResourceManager.GetString("EntityExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fathers full name.
        /// </summary>
        public static string FathersName {
            get {
                return ResourceManager.GetString("FathersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fathers profession.
        /// </summary>
        public static string FathersProfession {
            get {
                return ResourceManager.GetString("FathersProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;Jump to first.
        /// </summary>
        public static string FirstPageButton {
            get {
                return ResourceManager.GetString("FirstPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FoodQuality.
        /// </summary>
        public static string FoodQuality {
            get {
                return ResourceManager.GetString("FoodQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Next.
        /// </summary>
        public static string ForwardButton {
            get {
                return ResourceManager.GetString("ForwardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting title date.
        /// </summary>
        public static string GettingTitleDate {
            get {
                return ResourceManager.GetString("GettingTitleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give receipt.
        /// </summary>
        public static string GiveReceipt {
            get {
                return ResourceManager.GetString("GiveReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inland water quality.
        /// </summary>
        public static string InlandWaterQualtiy {
            get {
                return ResourceManager.GetString("InlandWaterQualtiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance number.
        /// </summary>
        public static string InsuranceNumber {
            get {
                return ResourceManager.GetString("InsuranceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;Jump to last.
        /// </summary>
        public static string LastPageButton {
            get {
                return ResourceManager.GetString("LastPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marriage status.
        /// </summary>
        public static string MarriageStatus {
            get {
                return ResourceManager.GetString("MarriageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical records.
        /// </summary>
        public static string MedicalRecordsReview {
            get {
                return ResourceManager.GetString("MedicalRecordsReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical title.
        /// </summary>
        public static string MedicalTitle {
            get {
                return ResourceManager.GetString("MedicalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical titles.
        /// </summary>
        public static string MedicalTitles {
            get {
                return ResourceManager.GetString("MedicalTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical vaste information.
        /// </summary>
        public static string MedicalVasteInformation {
            get {
                return ResourceManager.GetString("MedicalVasteInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mothers  full name.
        /// </summary>
        public static string MothersName {
            get {
                return ResourceManager.GetString("MothersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mothers profession.
        /// </summary>
        public static string MothersProfession {
            get {
                return ResourceManager.GetString("MothersProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise information.
        /// </summary>
        public static string NoiseInformation {
            get {
                return ResourceManager.GetString("NoiseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot login without role in
        ///system, and you have non..
        /// </summary>
        public static string NoKnownRoles {
            get {
                return ResourceManager.GetString("NoKnownRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not married.
        /// </summary>
        public static string NotMarried {
            get {
                return ResourceManager.GetString("NotMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past clinics.
        /// </summary>
        public static string PastClinics {
            get {
                return ResourceManager.GetString("PastClinics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient control.
        /// </summary>
        public static string PatientControl {
            get {
                return ResourceManager.GetString("PatientControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        public static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put in record.
        /// </summary>
        public static string PutInRecord {
            get {
                return ResourceManager.GetString("PutInRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiation.
        /// </summary>
        public static string Radiation {
            get {
                return ResourceManager.GetString("Radiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreational water quality.
        /// </summary>
        public static string RecreationalWaterQuality {
            get {
                return ResourceManager.GetString("RecreationalWaterQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residance place.
        /// </summary>
        public static string ResidancePlace {
            get {
                return ResourceManager.GetString("ResidancePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing results.
        /// </summary>
        public static string ShowingResults {
            get {
                return ResourceManager.GetString("ShowingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since.
        /// </summary>
        public static string Since {
            get {
                return ResourceManager.GetString("Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain quality.
        /// </summary>
        public static string TerrainQuality {
            get {
                return ResourceManager.GetString("TerrainQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UBN.
        /// </summary>
        public static string UBN {
            get {
                return ResourceManager.GetString("UBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has been successfully updated..
        /// </summary>
        public static string UpdatingSuccess {
            get {
                return ResourceManager.GetString("UpdatingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual assistant.
        /// </summary>
        public static string VirtualAssistant {
            get {
                return ResourceManager.GetString("VirtualAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work experience.
        /// </summary>
        public static string WorkExperience {
            get {
                return ResourceManager.GetString("WorkExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given data is not valid.
        ///For safety of the account you are
        ///trying to access, the exact error will
        ///not be given..
        /// </summary>
        public static string WrongPasswordOrEmail {
            get {
                return ResourceManager.GetString("WrongPasswordOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
